---
# tasks file for jenkins
 - name: Download Jenkins apt URL for Ubuntu
   apt_key:
      url: "{{jenkins.repo_URL}}"
      state: present
   become: yes

 - name: Ensure the Jenkins repository is configured
   apt_repository: 
      repo='https://pkg.jenkins.io/debian-stable binary/'
      state: present
   become: yes

 - name: Update apt Cache
   apt: 
      update_cache: yes
      state: latest

 - name: Ensure Open Java 11 JDK is present - Install Java 11
   apt:
      name: "{{java}}"
      state: present

 - name: Install Jenkins
   apt:
      name: jenkins
      state: latest

 - name: Start Jenkins service
   service:
      name: jenkins
      enabled: true
      state: started



